sculpin:
  ignore:
    - _assets/

sculpin_content_types:
  posts:
    enabled: false
  albums:
    type: path
    path: _albums
    singular_name: album
    layout: album
    permalink: albums/:basename/
    enabled: true
    taxonomies:
      - tags
