version: 2.1

jobs:
#  build_server:
#    docker:
#      - image: php:7.4-cli
#    steps:
#      - checkout
#      - run: shards install
#      - run: make spec STAGE=prod
#      - run: make build STAGE=prod
#      - persist_to_workspace:
#          root: build
#          paths: ['*']

  build_assets:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run: npm ci
      - run: npm run-script build-prod
      - run: ls -la ./output_prod/static
      - persist_to_workspace:
          root: output_prod/static
          paths: ['*']


workflows:
  version: 2
  test_and_build:
    jobs:
#      - build_server
      - build_assets
#      - build_docker_image:
#          requires:
#            - build_server
#            - build_assets
#          filters:
#            branches:
#              only: master
#      - deploy_app:
#          requires:
#            - build_docker_image
#          filters:
#            branches:
#              only: master
