version: 2.1

jobs:
  build_assets:
    docker:
      - image: node:12-alpine
    environment:
      OUTPUT_DIR: ./output_prod/static
    steps:
      - checkout
      - run: npm ci
      - run: mkdir -p ${OUTPUT_DIR}
      - run: npm run-script build-prod
      - run: ls -la ${OUTPUT_DIR}
      - run: mkdir -p /tmp/workspace/static
      - run: cp -R ${OUTPUT_DIR}/* /tmp/workspace/static
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - static/*

  build_html:
    docker:
      - image: php:7.4-cli
    environment:
      APP_ENV: prod
      APP_URL: https://vakhrushev.me
      STATIC_DIR: ./output_prod/static
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: docker/provision.sh
      - run: composer install --no-interaction --no-progress
      - run: mkdir -p ${STATIC_DIR}
      - run: cp -R /tmp/workspace/static/* ${STATIC_DIR}
      - run: |
          ./vendor/bin/sculpin generate \
            --env="${APP_ENV}" \
            --url="${APP_URL}" \
            --no-interaction \
            -vv
      - run: mkdir -p /tmp/workspace/html
      - run: cp -R ./output_prod/* /tmp/workspace/html
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - html/*

workflows:
  version: 2
  test_and_build:
    jobs:
      - build_assets
      - build_html:
          requires:
            - build_assets
#      - build_docker_image:
#          requires:
#            - build_server
#            - build_assets
#          filters:
#            branches:
#              only: master
#      - deploy_app:
#          requires:
#            - build_docker_image
#          filters:
#            branches:
#              only: master
