version: '2'

services:
  nginx:
    image: '${NGINX_IMAGE}'
#    user: '${CURRENT_UID}:${CURRENT_GID}'
    restart: unless-stopped
    ports:
      - '${WEB_SERVER_PORT}:80'
    env_file:
      - .env
