---
- hosts: all

  vars:
    application_root: /vagrant

    timezone: UTC

    nginx_conf_name: anwinged.conf
    nginx_conf_root: '{{ application_root }}/output_dev'
    nginx_conf_domain: anwinged.ru
    nginx_conf_sendfile: false

    nginx_remove_default_vhost: true

    php_enable_webserver: false
    php_packages:
      - php7.1
      - php7.1-mbstring
      - php7.1-intl
      - php7.1-curl
      - php7.1-xml


  pre_tasks:
    - name: Ensure that PHP Ondrej PPA is added
      apt_repository: repo=ppa:ondrej/php state=present

  roles:
    - yatesr.timezone
    - server
    - geerlingguy.nginx
    - nginx
    - geerlingguy.php
