#!/bin/bash

source .env

docker build \
    --file docker/php/Dockerfile \
    --tag "${PHP_IMAGE}" \
    "$PWD"

docker build \
    --file docker/node/Dockerfile \
    --tag "${NODE_IMAGE}" \
    "$PWD"
