#!/bin/bash

source .env

mkdir -p ./.composer/cache

docker run \
    --rm \
    --interactive \
    --tty \
    --user $UID:$(id -g) \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $PWD:/srv/homepage \
    --volume $PWD/.composer:/tmp/.composer \
    --env COMPOSER_HOME=/tmp/.composer \
    ${HOMEPAGE_IMAGE} composer "$@"
