#!/bin/bash

source .env

mkdir -p var/docker-cache/.composer

docker run \
    --rm \
    --interactive \
    --tty \
    --user "$UID:$(id -g)" \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $PWD:/srv/app \
    --volume $HOME:$HOME \
    --volume $PWD/var/docker-cache/.composer:/tmp/.composer \
    --env COMPOSER_HOME=/tmp/.composer \
    ${PHP_IMAGE} \
    composer "$@"
