#!/bin/bash

source .env

docker run \
    --rm \
    --interactive \
    --tty \
    --user "$UID" \
    --init \
	--volume="$PWD:/srv/homepage" \
	--expose=8000 \
	--publish=8000:8000 \
	${HOMEPAGE_IMAGE} \
	./vendor/bin/sculpin "$@"
